# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kvparam.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='kvparam.proto',
  package='kvdata',
  syntax='proto2',
  serialized_pb=_b('\n\rkvparam.proto\x12\x06kvdata\"U\n\x07kvparam\x12\x11\n\toperation\x18\x01 \x02(\x05\x12\x0b\n\x03key\x18\x02 \x02(\t\x12\r\n\x05value\x18\x03 \x01(\t\x12\x0e\n\x06length\x18\x04 \x01(\x05\x12\x0b\n\x03ret\x18\x05 \x01(\x05')
)




_KVPARAM = _descriptor.Descriptor(
  name='kvparam',
  full_name='kvdata.kvparam',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='operation', full_name='kvdata.kvparam.operation', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='key', full_name='kvdata.kvparam.key', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='kvdata.kvparam.value', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='length', full_name='kvdata.kvparam.length', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ret', full_name='kvdata.kvparam.ret', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=110,
)

DESCRIPTOR.message_types_by_name['kvparam'] = _KVPARAM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

kvparam = _reflection.GeneratedProtocolMessageType('kvparam', (_message.Message,), dict(
  DESCRIPTOR = _KVPARAM,
  __module__ = 'kvparam_pb2'
  # @@protoc_insertion_point(class_scope:kvdata.kvparam)
  ))
_sym_db.RegisterMessage(kvparam)


# @@protoc_insertion_point(module_scope)
