/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: kvparam.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "kvparam.pb-c.h"
void   kvdata__kvparam__init
                     (Kvdata__Kvparam         *message)
{
  static Kvdata__Kvparam init_value = KVDATA__KVPARAM__INIT;
  *message = init_value;
}
size_t kvdata__kvparam__get_packed_size
                     (const Kvdata__Kvparam *message)
{
  assert(message->base.descriptor == &kvdata__kvparam__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t kvdata__kvparam__pack
                     (const Kvdata__Kvparam *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &kvdata__kvparam__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t kvdata__kvparam__pack_to_buffer
                     (const Kvdata__Kvparam *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &kvdata__kvparam__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Kvdata__Kvparam *
       kvdata__kvparam__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Kvdata__Kvparam *)
     protobuf_c_message_unpack (&kvdata__kvparam__descriptor,
                                allocator, len, data);
}
void   kvdata__kvparam__free_unpacked
                     (Kvdata__Kvparam *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &kvdata__kvparam__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor kvdata__kvparam__field_descriptors[5] =
{
  {
    "operation",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Kvdata__Kvparam, operation),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "key",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Kvdata__Kvparam, key),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Kvdata__Kvparam, value),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "length",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Kvdata__Kvparam, has_length),
    offsetof(Kvdata__Kvparam, length),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ret",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Kvdata__Kvparam, has_ret),
    offsetof(Kvdata__Kvparam, ret),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned kvdata__kvparam__field_indices_by_name[] = {
  1,   /* field[1] = key */
  3,   /* field[3] = length */
  0,   /* field[0] = operation */
  4,   /* field[4] = ret */
  2,   /* field[2] = value */
};
static const ProtobufCIntRange kvdata__kvparam__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor kvdata__kvparam__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "kvdata.kvparam",
  "Kvparam",
  "Kvdata__Kvparam",
  "kvdata",
  sizeof(Kvdata__Kvparam),
  5,
  kvdata__kvparam__field_descriptors,
  kvdata__kvparam__field_indices_by_name,
  1,  kvdata__kvparam__number_ranges,
  (ProtobufCMessageInit) kvdata__kvparam__init,
  NULL,NULL,NULL    /* reserved[123] */
};
